version: '3'

services:
   oracledb:
     build:
       context: ./Dockerfiles/oracledb/
       dockerfile: Dockerfile
     image: condr/database
     restart: always
     ports:
      - "1521:1521"

   app:
     depends_on:
       - oracledb
     image: adrianharabula/php7-with-oci8
     links:
      - oracledb
     volumes:
      - ./app:/var/www/html
     ports:
      - "8080:80"

   devapp:
     depends_on:
       - oracledb
     build:
       context: ./Dockerfiles/php7cli/
       dockerfile: Dockerfile
     image: condr/php7cli
     links:
      - oracledb
     volumes:
      - ./app:/root/app
     ports:
      - "8000:8000"

   webhooks:
     build:
       context: ./Dockerfiles/git-webhook/
       dockerfile: Dockerfile
     image: adrianharabula/git-webhook
     restart: always
     volumes:
       - "./Dockerfiles/git-webhook/webhook/hooks.json:/etc/webhook/hooks.json"
       - "./Dockerfiles/git-webhook/webhook/scripts:/var/scripts"
       - ".:/root/condr"
     command: "-verbose -hooks=/etc/webhook/hooks.json -hotreload"
     ports:
      - "9000:9000"

   virtualhosts:
     build:
      context: ./Dockerfiles/apache-virtualhosts/
      dockerfile: Dockerfile
     image: apache-virtualhosts
     links:
      - app
      - webhooks
     ports:
      - "80:80"

volumes:
    www:
