version: '3'

services:
   oracledb:
     image: wnameless/oracle-xe-11g
     restart: always
     ports:
      - "1521:1521"

   app:
     depends_on:
       - oracledb
     image: adrianharabula/php7-with-oci8
     links:
      - oracledb
     volumes:
      - ./app:/var/www/html
     ports:
      - "8080:80"

   api:
     depends_on:
       - oracledb
     image: adrianharabula/php7-with-oci8
     links:
      - oracledb
     volumes:
      - ./api:/var/www/html
     ports:
      - "8181:80"

   psgbd_etapa2:
     depends_on:
       - oracledb
     image: adrianharabula/php7-with-oci8
     links:
      - oracledb
     volumes:
      - ./database_design/psgbd-etapa2:/var/www/html
     ports:
      - "8282:80"

volumes:
    www:
