CREATE VIEW SOFT_DELETE AS
SELECT *
FROM PRODUCTS;

create or replace TRIGGER SOFT_DELETE 
INSTEAD OF DELETE ON PRODUCTS_VIEW
BEGIN
  UPDATE PRODUCTS SET deleted_at = systimestamp;
  UPDATE PRODUCTS_VIEW SET deleted_at = systimestamp;
END;