title: ConDr (Consumer Decision Maker)
description: Proiect realizat în cadrul materiei Tehnologii Web, an univ. 2016-2017, Facultatea de Informatică din Iaşi
show_downloads: true
google_analytics:
theme: 
